-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-12-10 18:16:27 CET
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c
-- Lukasz Stanecki 310978
-- Arda Derbent 317052


DROP TABLE art_enthusiast CASCADE CONSTRAINTS;

DROP TABLE art_piece CASCADE CONSTRAINTS;

DROP TABLE artist CASCADE CONSTRAINTS;

DROP TABLE auction CASCADE CONSTRAINTS;

DROP TABLE auction_to_art_enthusiast CASCADE CONSTRAINTS;

DROP TABLE painting CASCADE CONSTRAINTS;

DROP TABLE photography CASCADE CONSTRAINTS;

DROP TABLE purchase CASCADE CONSTRAINTS;

DROP TABLE purchase_detail CASCADE CONSTRAINTS;

DROP TABLE sculpture CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE art_enthusiast (
    ssn                 VARCHAR2(11 CHAR) NOT NULL,
    art_enthusiast_name VARCHAR2(50 CHAR) NOT NULL,
    enthusiast_address  VARCHAR2(50 CHAR) NOT NULL,
    contact_information VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE art_enthusiast ADD CONSTRAINT art_enthusiast_pk PRIMARY KEY ( ssn );

CREATE TABLE art_piece (
    id             NUMBER(9) NOT NULL,
    art_piece_name VARCHAR2(30 CHAR) NOT NULL,
    sizes          VARCHAR2(20 CHAR) NOT NULL,
    century        VARCHAR2(10 CHAR),
    originality    VARCHAR2(10 CHAR) NOT NULL,
    starting_price NUMBER(10, 2),
    artist_id      NUMBER(9) NOT NULL
);

ALTER TABLE art_piece ADD CONSTRAINT art_piece_pk PRIMARY KEY ( id );

CREATE TABLE artist (
    id               NUMBER(9) NOT NULL,
    artist_name      VARCHAR2(30 CHAR) NOT NULL,
    country_of_birth VARCHAR2(20 CHAR),
    date_of_birth    DATE
);

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( id );

CREATE TABLE auction (
    auction_number NUMBER(9) NOT NULL,
    auction_date   DATE NOT NULL,
    art_piece_id   NUMBER(9) NOT NULL
);

ALTER TABLE auction ADD CONSTRAINT auction_pk PRIMARY KEY ( auction_number );

CREATE TABLE auction_to_art_enthusiast (
    auction_number     NUMBER(9) NOT NULL,
    art_enthusiast_ssn VARCHAR2(11 CHAR) NOT NULL
);

ALTER TABLE auction_to_art_enthusiast ADD CONSTRAINT auction_to_art_enthusiast_pk PRIMARY KEY ( auction_number,
                                                                                                art_enthusiast_ssn );

CREATE TABLE painting (
    paints_used      VARCHAR2(20 CHAR),
    type_of_painting VARCHAR2(20 CHAR),
    art_piece_id     NUMBER(9) NOT NULL
);

ALTER TABLE painting ADD CONSTRAINT painting_pk PRIMARY KEY ( art_piece_id );

CREATE TABLE photography (
    type_of_photography VARCHAR2(20 CHAR),
    color               VARCHAR2(20 CHAR),
    art_piece_id        NUMBER(9) NOT NULL
);

ALTER TABLE photography ADD CONSTRAINT photography_pk PRIMARY KEY ( art_piece_id );

CREATE TABLE purchase (
    purchase_number    NUMBER(9) NOT NULL,
    purchase_date      DATE NOT NULL,
    art_enthusiast_ssn VARCHAR2(11 CHAR) NOT NULL
);

ALTER TABLE purchase ADD CONSTRAINT purchase_pk PRIMARY KEY ( purchase_number );

CREATE TABLE purchase_detail (
    detail_id       NUMBER(9) NOT NULL,
    price           NUMBER(10, 2) NOT NULL,
    purchase_number NUMBER(9) NOT NULL,
    art_piece_id    NUMBER(9) NOT NULL
);

ALTER TABLE purchase_detail ADD CONSTRAINT purchase_detail_pk PRIMARY KEY ( detail_id );

CREATE TABLE sculpture (
    material_used VARCHAR2(20 CHAR),
    art_piece_id  NUMBER(9) NOT NULL
);

ALTER TABLE sculpture ADD CONSTRAINT sculpture_pk PRIMARY KEY ( art_piece_id );

ALTER TABLE art_piece
    ADD CONSTRAINT art_piece_artist_fk FOREIGN KEY ( artist_id )
        REFERENCES artist ( id );

ALTER TABLE auction
    ADD CONSTRAINT auction_art_piece_fk FOREIGN KEY ( art_piece_id )
        REFERENCES art_piece ( id );

ALTER TABLE auction_to_art_enthusiast
    ADD CONSTRAINT auction_to_art_enthusiast_fk FOREIGN KEY ( art_enthusiast_ssn )
        REFERENCES art_enthusiast ( ssn );

ALTER TABLE auction_to_art_enthusiast
    ADD CONSTRAINT auction_to_art_enthusiast_fk FOREIGN KEY ( auction_number )
        REFERENCES auction ( auction_number );

ALTER TABLE painting
    ADD CONSTRAINT painting_art_piece_fk FOREIGN KEY ( art_piece_id )
        REFERENCES art_piece ( id )
            ON DELETE CASCADE;

ALTER TABLE photography
    ADD CONSTRAINT photography_art_piece_fk FOREIGN KEY ( art_piece_id )
        REFERENCES art_piece ( id )
            ON DELETE CASCADE;

ALTER TABLE purchase
    ADD CONSTRAINT purchase_art_enthusiast_fk FOREIGN KEY ( art_enthusiast_ssn )
        REFERENCES art_enthusiast ( ssn );

ALTER TABLE purchase_detail
    ADD CONSTRAINT purchase_detail_art_piece_fk FOREIGN KEY ( art_piece_id )
        REFERENCES art_piece ( id );

ALTER TABLE purchase_detail
    ADD CONSTRAINT purchase_detail_purchase_fk FOREIGN KEY ( purchase_number )
        REFERENCES purchase ( purchase_number )
            ON DELETE CASCADE;

ALTER TABLE sculpture
    ADD CONSTRAINT sculpture_art_piece_fk FOREIGN KEY ( art_piece_id )
        REFERENCES art_piece ( id )
            ON DELETE CASCADE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
